DROP DATABASE IF EXISTS vlabs;
CREATE DATABASE vlabs;
CREATE USER 'vlabs'@'localhost' IDENTIFIED BY 'vlabs';
GRANT ALL PRIVILEGES ON vlabs.* TO 'vlabs'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
